---
- name: Ensure custom public styles are present
  ansible.builtin.copy:
    src: "{{ gin_public_files }}"
    dest: /srv/gin/config/gogs
    owner: ginuser
    group: ginservice
  notify:
    - Restart gin

- name: Ensure custom templates are present
  ansible.builtin.copy:
    src: templates
    dest: /srv/gin/config/gogs
    owner: ginuser
    group: ginservice
  notify:
    - Restart gin

# By calling flush_handlers, we make sure the handler is run *right now*
- name: Ensure gin is restarted if needed
  meta: flush_handlers
